-- 1. Count the number of sales transactions for each product.  
-- 2. Find the average sale amount for each product.  
-- 3. Find the maximum and minimum sale amount for each product.  
-- 4. Find the total revenue generated by each product.  
-- 5. Count the number of sales transactions for each customer.  
-- 6. Find the average sale amount per customer.  
-- 7. Find the highest purchase amount for each customer.  
-- 8. Find the lowest purchase amount for each customer.  
-- 9. Find the total revenue generated by each store location.  
-- 10. Count the number of sales transactions for each region.  
-- 11. Find the total revenue per region.  
-- 12. Find the average sale amount per region.  
-- 13. Count the number of sales per month.  
-- 14. Find the total revenue per month.  
-- 15. Find the product that generated the highest revenue.  
-- 16. Find the most frequently purchased product.  
-- 17. Find the most valuable customer based on total spending.  
-- 18. Find the total revenue per sales channel (e.g., online vs. offline).  
-- 19. Count the number of sales for each payment method.  
-- 20. Find the total revenue generated per payment method. 

------------------------------------------------------
-- 1. Count the number of sales transactions for each product.  
select PROD_ID,count(AMOUNT_SOLD) as total_sales_trasn from sh.sales
group by PROD_ID;

--Find the average sale amount for each product.  

select PROD_ID,avg(AMOUNT_SOLD) as avg_sales from sh.sales
group by PROD_ID;

--Find the maximum and minimum sale amount for each product. 
select PROD_ID,max(AMOUNT_SOLD) as max_sales,min(AMOUNT_SOLD) as min_sales from sh.sales
group by PROD_ID;

--Find the total revenue generated by each product.  
select PROD_ID,sum(AMOUNT_SOLD) as total_sales from sh.sales
group by PROD_ID;

--Count the number of sales transactions for each customer. 
select CUST_ID,count(AMOUNT_SOLD) number_of_sales  from sh.SALES
group by CUST_ID;

--Find the highest purchase amount for each customer. 
select CUST_ID,MAX(AMOUNT_SOLD) max_purchase_for_each_customer  from sh.SALES
group by CUST_ID;

--Find the highest purchase amount for each customer. 
select CUST_ID,MIN(AMOUNT_SOLD) min_purchase_for_each_customer  from sh.SALES
group by CUST_ID;

--Find the total revenue generated by each store location.
select cust_city,sum(AMOUNT_SOLD) as total_reven_by_loc from sh.customers cu
join sh.sales sa on cu.CUST_ID =sa.CUST_ID
group by cust_city;

-- 10. Count the number of sales transactions for each region.
select country_region,count(AMOUNT_SOLD) as num_of_trans_region from sh.countries co
join sh.customers cu on co.COUNTRY_ID =cu.COUNTRY_ID 
join sh.sales sa on cu.CUST_ID = sa.CUST_ID
group by country_region;

-- 11. Find the total revenue per region.  
select country_region,sum(AMOUNT_SOLD) as total_reven_by_region from sh.countries co
join sh.customers cu on co.COUNTRY_ID =cu.COUNTRY_ID 
join sh.sales sa on cu.CUST_ID = sa.CUST_ID
group by country_region;

-- 12. Find the average sale amount per region. 
select country_region,avg(AMOUNT_SOLD) as total_reven_by_region from sh.countries co
join sh.customers cu on co.COUNTRY_ID =cu.COUNTRY_ID 
join sh.sales sa on cu.CUST_ID = sa.CUST_ID
group by country_region;

--Count the number of sales per month. 
select EXTRACT(MONTH FROM TIME_ID) AS Month,count(AMOUNT_SOLD)as sales_per_month
from SH.SALES
group by Month; 

-- 14. Find the total revenue per month.  
select EXTRACT(MONTH FROM TIME_ID) AS Month,sum(AMOUNT_SOLD)as sales_per_month
from SH.SALES
group by Month; 

--Find the product that generated the highest revenue. 
select PROD_ID,sum(AMOUNT_SOLD) sum_total from SH.sales
group by PROD_ID
order by sum_total desc
fetch first 1 row only;

-- 16. Find the most frequently purchased product.  
select PROD_ID,sum(Quantity_sold) amount  from SH.sales
group by PROD_ID
order by amount desc
fetch first 1 row only;

-- 17. Find the most valuable customer based on total spending.
select CUST_ID,SUM(AMOUNT_SOLD) as total_rev_from_cust
from SH.sales
group by CUST_ID
order by total_rev_from_cust desc
fetch first 1 row only;

-- 18. Find the total revenue per sales channel (e.g., online vs. offline).
select CHANNEL_ID , sum(AMOUNT_SOLD) amount_per_channel from SH.sales
group by CHANNEL_ID;

-- 19. Count the number of sales for each payment method.  

select CHANNEL_ID , count(QUANTITY_SOLD) sales_count from SH.sales
group by CHANNEL_ID;

-- 20. Find the total revenue generated per payment method. 
select CHANNEL_ID as payment_id, sum(AMOUNT_SOLD) total_amount_per_payment from SH.sales
group by CHANNEL_ID;